### ISSUE TITLE
HTML best practices

### ISSUE THREAD

**Issue by bamsi** [JauJau088/My-Portfolio#5]
I think you could have used `<li>` only and added up classes instead of having to `<span>` inside the list to make your code more readable.

**Comment by JauJau088** [comment]
Yes, I didn't have any specific reason for using `<span>` there. Thank you for the tip, will definitely make the change on the next pull request. 🙏

**Comment by JauJau088** [comment]
Resolved in this [Pull Request](https://github.com/JauJau088/My-Portfolio/pull/7) ✔️
